### ISSUE TITLE
Fallo de enlace en "Gestionando los Services"

### ISSUE THREAD

**Issue by Ganso** [iesgn/curso_kubernetes_cep#16]
En el apartado "Service ClusterIP" se enlaza a "[mariad-srv](https://github.com/iesgn/curso_kubernetes_cep/blob/main/modulo6/files/mariad-srv.yaml)" en lugar de a "[mariadb-srv](https://github.com/iesgn/curso_kubernetes_cep/blob/main/modulo6/files/mariadb-srv.yaml)".

**Comment by albertomolina** [comment]
Gracias Javi. Corregido
