### ISSUE TITLE
Estrategias de despliegues

### ISSUE THREAD

**Issue by josedom24** [iesgn/curso_kubernetes_cep#18]
Esta mañana con los alumnos me he dado cuenta que han cambiado la estrategia por defecto a RollingUpdate.
Además ahora mirando la documentación he visto algo nuevo que está mañana también he notado.
Los parámetros de RollingUpdate maxSurge y maxUnavailable.

Estos parámetros introducen el concepto de despliegue escalonado.
https://kubernetes.io/es/docs/concepts/workloads/controllers/deployment/#escalar-un-deployment

Habría que modificar la documentación para indicar que la estrategia por defecto es la RollingUpdate y decidir si vamos a hablar de los dos parámetros y del despliegues escalonados.

**Comment by albertomolina** [comment]
Yo no entraría en detalles sobre las estrategias de despliegue. Con modificar la doc y poner que la estrategia por defecto es RollingUpdate es suficiente. Y si me apuras, se puede hasta quitar y no comentar nada (es un tema realmente avanzado para verlo bien)

**Comment by josedom24** [comment]
Ok, muy bien. Opina lo mismo.
