### ISSUE TITLE
Imágenes de mediawiki en el módulo 5

### ISSUE THREAD

**Issue by josedom24** [iesgn/curso_kubernetes_cep#4]
Hay que hacer de nuevo el ejercicio del apartado [Actualización de un Deployment (rollout y rollback)](https://github.com/iesgn/curso_kubernetes_cep/blob/main/modulo5/actualizacion_deployment.md). La última vez que instale la mediawiki, el logo había cambiado.

Por lo tanto hay que acordarse de hacer de nuevo el ejercicio para capturar las imágenes con el nuevo logo.

**Comment by albertomolina** [comment]
Ya están actualizados, pero lo que no he encontrado es la licencia que tienen. El anterior logo sí tenía licencia de dominio público: https://commons.wikimedia.org/wiki/File:MediaWiki_logo_1.svg
